version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "quanticsoul4772"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "@vitest/*"
          - "eslint*"
          - "prettier*"
          - "husky"
          - "lint-staged"
          - "commitlint*"
        update-types:
          - "minor"
          - "patch"
      testing-dependencies:
        patterns:
          - "*testing*"
          - "vitest"
          - "msw"
          - "supertest"
        update-types:
          - "minor"
          - "patch"