# Configuration for PR labeler action
# Add labels based on file paths

documentation:
  - '**/*.md'
  - docs/**/*
  - LICENSE
  - .github/**/*.md

github-actions:
  - .github/workflows/**/*
  - .github/actions/**/*

dependencies:
  - package.json
  - package-lock.json
  - yarn.lock
  - pnpm-lock.yaml

typescript:
  - '**/*.ts'
  - '**/*.tsx'
  - tsconfig.json
  - tsconfig.*.json

testing:
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/*.test.js'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
  - '**/*.spec.js'
  - __tests__/**/*
  - test/**/*
  - tests/**/*
  - jest.config.*
  - vitest.config.*

security:
  - .github/workflows/security.yml
  - .github/dependabot.yml
  - src/validation.ts
  - src/auth/**/*
  - '**/*security*'
  - '**/*auth*'
  - '**/*token*'

api:
  - src/handlers/**/*
  - src/services/**/*
  - src/api/**/*
  - '**/*api*'

configuration:
  - .eslintrc*
  - .prettierrc*
  - .gitignore
  - .editorconfig
  - .env.example
  - config/**/*

docker:
  - Dockerfile
  - docker-compose.yml
  - .dockerignore

infrastructure:
  - terraform/**/*
  - k8s/**/*
  - helm/**/*
  - .github/workflows/release.yml
  - .github/workflows/deploy.yml
