apiVersion: v1
kind: ConfigMap
metadata:
  name: github-mcp-config
  namespace: github-mcp
  labels:
    app: github-mcp
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  GITHUB_READ_ONLY: "false"
  GITHUB_TOOLSETS: "all"
  # GITHUB_HOST: ""  # Uncomment for GitHub Enterprise